//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CombineAgricultureFarm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CropStorage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CropStorage()
        {
            this.CropSells = new HashSet<CropSell>();
        }
    
        public int CropStorageId { get; set; }
        public int FarmingDetailId { get; set; }
        public int CropStorage1 { get; set; }
        public Nullable<int> CropSell { get; set; }
        public System.DateTime StorageDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CropSell> CropSells { get; set; }
        public virtual FarmingDetailforCrop FarmingDetailforCrop { get; set; }
    }
}
