//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CombineAgricultureFarm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FarmInformation
    {
        public int FarminformationId { get; set; }
        public int SessionInfoId { get; set; }
        public int ClientId { get; set; }
        public int FurmingTypeId { get; set; }
        public int CropInfod { get; set; }
    
        public virtual ClientInformation ClientInformation { get; set; }
        public virtual CropInformation CropInformation { get; set; }
        public virtual FarmingSessionInfo FarmingSessionInfo { get; set; }
        public virtual FarmingType FarmingType { get; set; }
        public virtual FarmingDetailforCrop FarmingDetailforCrop { get; set; }
    }
}
